### ISSUE TITLE
token has expired (UNAUTHORIZED)

### ISSUE THREAD

**Issue by adriacidre** [joinself/self-ruby-sdk#275]
In some situations, a request to the api may respond with an exception
```
E, [2023-02-23T08:07:12.800537 #77429] ERROR -- SelfSDK examples: identity response : UNAUTHORIZED : error validating token
#<Thread:0x0000000146fcaf48 /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/messaging.rb:298 run> terminated with exception (report_on_exception is true):
/Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/client.rb:56:in `devices': you need connection permissions (RuntimeError)
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/messaging.rb:136:in `block in send_custom'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/messaging.rb:135:in `each'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/messaging.rb:135:in `send_custom'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/messaging.rb:92:in `send'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/chat.rb:215:in `block in send'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/chat.rb:214:in `each'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/chat.rb:214:in `send'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/chat.rb:40:in `message'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/chat/message.rb:96:in `message'
	from entity.rb:25:in `block in <main>'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/services/chat.rb:53:in `block in on_message'
	from /Users/adriancidrejugo/go/src/github.com/joinself/self-ruby-sdk/lib/messaging.rb:299:in `block in notify_observer'
```
this is hiding the original problem exposed on the api logs `error validating token : token has expired`.

In this specific case the problem is related to the client going idle for a determined period of time, so the workflow looks basically like:
```
- [x] prepare the auth token
- [x] prepare the request
- [x] connection goes idle, for a determined amount of time
```
When the system and the connection recover, the execution of this request continues, however, the used token is already expired, which causes that problem on the api.

The real problem here, is the api is not returning a specific error here, and instead an `UNAUTHORIZED` message, so there is no way on the client side to properly distinguish and manage this problem.

Once the api implements a return of a custom error, it should be possible for this sdk _(and possibly the same for others)_ to retry the http request.

**Comment by adriacidre** [comment]
I've made a proposal to provide better api error codes without breaking the compatibility with the current responses, you can find the details [here](https://github.com/joinself/self-api/pull/92).

Basically responses can provide a new optional field `error_id` like:
```
{"error_code":404, "error_id": "token_expired", "message":"identity not found"}
```

In this case we're looking for the `token_expired` error_id which will indicate the auth token provided is expired and we will have to retry the request.
